#!/bin/bash
echo "🚀 Activating Intelligent PDF-to-MD Engine v2.2..."
echo "🖥️  OS: bazzite"
echo "🧠 Hardware: HIGH_PERFORMANCE"
echo "🐍 Python: 3.12.12"
source venv/bin/activate
echo "✅ Environment activated!"
echo ""
echo "Available commands:"
echo "  python main.py                  - Process PDFs with auto-optimization"
echo "  python run_enhanced.py          - Enhanced processing"
echo "  python comprehensive_audit.py   - Project health check"
echo "  python verify_project.py        - Quick verification"
echo ""
echo "📚 Enhanced Features:"
echo "   • Quality assessment and iterative refinement"
echo "   • Stream-based processing (markitdown)"
echo "   • Form-style table detection"
echo "   • Partial numbering merge"
echo "   • Intelligent content analysis"
echo "   • Multi-strategy extraction"
echo ""
