#!/usr/bin/env python3
"""
state_sync.py — propose diffs to campaign/state.md from session logs.

Reads campaign/sessions/*.md for trigger events ("World events triggered"
section per session-template) and suggests updates to campaign/state.md.

Triggers recognized (regex, case-insensitive):
  - "March Clock":   Day X → Day Y      → update §2/§0 march clock
  - "Ritual Clock":  n/18 → m/18        → update ritual counter
  - "Regiarix killed", "Saarvith killed", "Zalkatar killed", "Ghostlord ..."
    → NPC status change in §0/§NPC
  - "Sonjak escaped/killed", "Salvatore ...", etc.
  - Alliance changes: "druidi confermati", "Dauth +N", "Rethmar +N", etc.

Output is a MARKDOWN DIFF REPORT, never overwriting state.md automatically.
The DM reviews and applies. Zero risk of corrupting canon.

Usage:
    python3 scripts/state_sync.py                      # scan all sessions, print report
    python3 scripts/state_sync.py --since 2026-01-01   # only after date
    python3 scripts/state_sync.py --session FILE.md    # only one file
"""
from __future__ import annotations
import sys, re, argparse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from dmcore import frontmatter  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SESS = ROOT / "campaign" / "sessions"
STATE = ROOT / "campaign" / "state.md"

DATE_RE = re.compile(r"(\d{4}-\d{2}-\d{2})")

TRIGGERS = [
    ("march_clock", re.compile(r"\*\*March Clock\*\*\s*:\s*Day\s*(\d+)\s*(?:→|->)\s*Day\s*(\d+)", re.I)),
    ("ritual_clock", re.compile(r"\*\*Ritual Clock[^*]*\*\*\s*:\s*(\d+)\s*/\s*18\s*(?:→|->)\s*(\d+)\s*/\s*18", re.I)),
    ("villain_clock", re.compile(r"(?:Sonjak|Salvatore|Sal|Azarr Kul|Ghostlord|Rakshasa|Sethrax|Tempestas)\s*(\d+)\s*(?:→|->)\s*(\d+)", re.I)),
    ("npc_killed", re.compile(r"(Regiarix|Saarvith|Zalkatar|Wyrmlord [A-Z][a-zA-Z]+|Ghostlord|Sonjak|Salvatore|Azarr Kul|Sethrax|Tempestas|Maewen|Lythiel|Lorana)\s*(?:is\s+)?(?:killed|dead|slain|morto|uccis[oa])", re.I)),
    ("npc_escaped", re.compile(r"(Sonjak|Salvatore|Sethrax|Tempestas|[A-Z][a-zA-Z]+)\s*(?:escaped|fled|fugg[aiì])", re.I)),
    ("alliance", re.compile(r"(Dauth|Rethmar|Starsong|Druidi|Cerchio|Ghostlord|Elfi|Nani)\s*[:\-]?\s*([+\-]?\d+)", re.I)),
]

def parse_event_block(text: str) -> str:
    m = re.search(r"##\s*World events triggered\s*\n(.*?)(?=\n##\s|\Z)", text, re.DOTALL | re.I)
    return m.group(1) if m else ""

def extract_events(path: Path) -> dict:
    """Delta della sessione. Preferisce il **front-matter** (dati) alle regex (prosa).

    ADR-0017 / lotto G2-ter: se il log porta un blocco `---` iniziale con
    `delta:`, quello è la fonte — deterministica, e non limitata alla lista di
    villain cablata in TRIGGERS. Senza front-matter si ricade sulle regex, così
    i log già scritti continuano a funzionare senza essere riscritti.
    """
    text = path.read_text(encoding="utf-8", errors="replace")
    m = DATE_RE.search(path.name) or DATE_RE.search(text[:400])
    date = m.group(1) if m else "0000-00-00"

    fm, body = frontmatter.split(text)
    block = parse_event_block(body)
    hits = frontmatter.deltas(fm)
    source = "front-matter" if hits else "regex"
    if not hits:
        for name, rx in TRIGGERS:
            for mm in rx.finditer(block):
                hits.append((name, mm.group(0).strip(), mm.groups()))
    return {"file": path.name, "date": date, "block": block.strip(),
            "hits": hits, "source": source}

def render_report(events: list[dict]) -> str:
    out = []
    out.append("# state.md — sync proposals\n")
    out.append("*Generated by `scripts/state_sync.py`. Review each block, then "
               "apply by hand to `campaign/state.md`. Nothing is written "
               "automatically — canon is yours to curate.*\n")
    if not events:
        out.append("\n*(No sessions with `## World events triggered` found.)*\n")
        return "\n".join(out)
    for ev in events:
        out.append(f"\n## 📅 {ev['date']} — `{ev['file']}`\n")
        if not ev["hits"]:
            out.append("_(no canonical triggers matched; review the block manually below)_\n")
        else:
            out.append("### Detected triggers\n")
            out.append("| Kind | Raw | Parsed |")
            out.append("|---|---|---|")
            for name, raw, groups in ev["hits"]:
                gs = " / ".join(str(g) for g in groups if g)
                out.append(f"| `{name}` | {raw} | {gs} |")
            out.append("\n### Suggested state.md edits\n")
            for name, raw, groups in ev["hits"]:
                out.append(_suggest(name, groups))
        out.append("\n<details><summary>Full World events block</summary>\n\n```\n" + (ev["block"] or "(empty)") + "\n```\n</details>\n")
    out.append("\n---\n*Tip: see `00_Red Hand Of Doom/Armate-CALCOLI-ESERCITI-DINAMICI.md §4` "
               "for canonical army deltas triggered by each event.*\n")
    return "\n".join(out)

def _suggest(name: str, g: tuple) -> str:
    if name == "march_clock":
        a, b = g
        return (f"- **§0 dashboard / §3 March Clock** → set March Clock to **Day {b}** "
                f"(from Day {a}; Δ = {int(b)-int(a)}). Check `Armate-SINCRONIZZAZIONE-CAMPAGNA.md` "
                f"waypoint ledger for faction/movement updates at Day {b}.")
    if name == "ritual_clock":
        a, b = g
        return (f"- **§0 dashboard / §NPC Azarr Kul** → advance Ritual Clock **{a}/18 → {b}/18**. "
                f"If ≥ 12/18, trigger 'rituale imminente' narrative warnings.")
    if name == "villain_clock":
        a, b = g
        return (f"- **§NPC villain clock** → advance villain step **{a} → {b}**. "
                f"Update the affected NPC's status line.")
    if name == "npc_killed":
        who = g[0]
        return (f"- **§NPC / §0 roster** → mark **{who}** as `status: dead`. "
                f"Check `campaign/npcs/` for file to amend. "
                f"If a faction leader, apply canonical morale hit per `Armate-CALCOLI §4`.")
    if name == "npc_escaped":
        who = g[0]
        return (f"- **§NPC** → mark **{who}** as `status: at large` and add a future hook.")
    if name == "alliance":
        who, delta = g
        return (f"- **§2 armies / alliances** → **{who}** roster/relation: apply delta **{delta}**. "
                f"Cross-ref canonical sums in `Armate-CALCOLI §3`.")
    return f"- (trigger `{name}` — manual review)"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--since", default=None, help="Only sessions on/after this YYYY-MM-DD")
    ap.add_argument("--session", default=None, help="Scan only this filename under campaign/sessions/")
    args = ap.parse_args()
    if not SESS.exists():
        print(f"[state_sync] No {SESS} — nothing to do."); return 0
    files = []
    if args.session:
        p = SESS / args.session
        if not p.exists():
            print(f"[state_sync] File not found: {p}", file=sys.stderr); return 2
        files = [p]
    else:
        files = sorted(SESS.glob("*.md"))
    events = []
    for p in files:
        ev = extract_events(p)
        if args.since and ev["date"] < args.since: continue
        if ev["hits"] or ev["block"]:
            events.append(ev)
    print(render_report(events))
    return 0

if __name__ == "__main__":
    sys.exit(main())
